### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by t0t07** [jamesward/cloudstate-sample-fraud#1]
When I `./gradlew run`, it is stuck at the 87%:

```
> Task :run
2020-11-09 23:22:08.432 INFO io.cloudstate.kotlinsupport.CloudStateRunner - Loading Config...
<===========--> 87% EXECUTING [4m 41s]
> :run
```

If I run `docker run -it --rm --network="host" cloudstateio/cloudstate-proxy-dev-mode -Dcloudstate.proxy.user-function-port=8080 -Dcloudstate.proxy.passivation-timeout=60m`, I will get into exception quickly

```
2020-11-10 07:25:46.144 INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-11-10 07:25:46.919 INFO akka.remote.artery.tcp.ArteryTcpTransport - Remoting started with transport [Artery tcp]; listening on address [akka://cloudstate-proxy@192.168.65.3:25520] with UID [5469536139706137754]
2020-11-10 07:25:46.966 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - Starting up, Akka version [2.6.9] ...
2020-11-10 07:25:47.059 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - Started up successfully
2020-11-10 07:25:47.163 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2020-11-10 07:25:47.179 INFO akka.cluster.sbr.SplitBrainResolver - SBR started. Config: stableAfter: 20000 ms, strategy: KeepMajority, selfUniqueAddress: UniqueAddress(akka://cloudstate-proxy@192.168.65.3:25520,5469536139706137754), selfDc: default
2020-11-10 07:25:47.518 INFO akka.actor.ActorSystemImpl - Starting Cloudstate Proxy version [0.0.0] running on [OpenJDK Runtime Environment 11.0.8+10]
2020-11-10 07:25:47.558 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - Node [akka://cloudstate-proxy@192.168.65.3:25520] is JOINING itself (with roles [dc-default]) and forming new cluster
2020-11-10 07:25:47.567 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - is the new leader among reachable nodes (more leaders may exist)
2020-11-10 07:25:47.617 INFO akka.cluster.Cluster - Cluster Node [akka://cloudstate-proxy@192.168.65.3:25520] - Leader is moving node [akka://cloudstate-proxy@192.168.65.3:25520] to [Up]
2020-11-10 07:25:47.648 INFO akka.cluster.sbr.SplitBrainResolver - This node is now the leader responsible for taking SBR decisions among the reachable nodes (more leaders may exist).
2020-11-10 07:25:48.662 ERROR akka.actor.OneForOneStrategy - UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:8080
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Any help? Thanks

**Comment by jamesward** [comment]
Thanks for trying this! My guess is that something I'm using version bumped to a new incompatible version.  Investigating now.

**Comment by jamesward** [comment]
Actually this was just because I forgot to push a commit.  :(  Sorry!
https://github.com/jamesward/cloudstate-sample-fraud/commit/927611b3127cd3af8cf4ccf58c037dc26a9241a2

Pull the latest and you should be good.

**Comment by jamesward** [comment]
Oh, sounds like it is something else. I suspect an issue with `--network="host"`

**Comment by jamesward** [comment]
For reference: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
